services:
  1p_api_prod:
    container_name: 1p_api_prod
    build:
      context: ../apps/api
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - APP_ENV=prod
      - PORT=35763
    restart: unless-stopped
    networks:
      - proxy

  1p_web_prod:
    container_name: 1p_web_prod
    build:
      context: ../apps/web
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    depends_on:
      - 1p_api_prod
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
