services:
  1p_api_st:
    container_name: 1p_api_st
    build:
      context: ../apps/api
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - APP_ENV=staging
      - PORT=35764
    restart: unless-stopped
    networks:
      - proxy

  1p_web_st:
    container_name: 1p_web_st
    build:
      context: ../apps/web
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    depends_on:
      - 1p_api_st
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
