services:
  nginx:
    image: nginx:alpine
    container_name: 1p_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    networks:
      - proxy

networks:
  proxy:
    external: true
